name: CogScenography
favicon: null
layout_spectrum: 0.94254
typography_spectrum: 0.4451051941141486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1542293766979128
  lightness: 0.7195331011898816
  saturation: 0.1358366198837757
  rhythmicContrast: 0.2803039082791656
purpose: []
