name: CogScenography
favicon: null
layout_spectrum: 0.94254
typography_spectrum: 0.4451051941141486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b8b8b6'
    - '#636363'
    - '#c16b68'
  brandStrength: 0.1542293766979128
  lightness: 0.7195331011898816
  saturation: 0.1358366198837757
  rhythmicContrast: 0.2803039082791656
purpose: []
