name: CogScenography
favicon: null
layout_spectrum: 0.77632
typography_spectrum: 0.52796
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090e12'
    - '#607497'
    - '#353d61'
    - '#b5b5b7'
    - '#cb9239'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
